[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "temperature-conversion-package"
version = "0.1.0"
description = "A simple temperature conversion package."
requires-python = ">=3.9"
authors = [
    { name = "S" }
]
keywords = ["temperature", "conversion", "celsius", "fahrenheit"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
]

dependencies = []

[project.scripts]
temperature-converter = "temperature_conversion.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/temperature_conversion"]