# -*- coding: utf-8 -*-
"""temperature cli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJqSeQfEwk0Td2AVICR7I_0r3duasUGx
"""

"""
CLI file for temperature conversion package
"""

import argparse

from temperature_conversion.core import celsius_to_fahrenheit, fahrenheit_to_celsius


def main() -> None:
    """
    Run the command-line interface.
    """
    parser = argparse.ArgumentParser(
        description="Convert temperatures between Celsius and Fahrenheit."
    )

    parser.add_argument(
        "value",
        type=float,
        help="Temperature value to convert.",
    )

    parser.add_argument(
        "--to",
        choices=["celsius", "fahrenheit"],
        required=True,
        help="Target temperature scale.",
    )

    args = parser.parse_args()

    if args.to == "fahrenheit":
        result = celsius_to_fahrenheit(args.value)
        print(result)

    elif args.to == "celsius":
        result = fahrenheit_to_celsius(args.value)
        print(result)


if __name__ == "__main__":
    main()