# -*- coding: utf-8 -*-
"""temp conversion core.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d9-a5a8xdydGJ7gNKulUbmPyyjhRccST
"""

def celsius_to_fahrenheit(celsius:float) -> float:
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit
def fahrenheit_to_celsius(fahrenheit:float) -> float:
    celsius = (fahrenheit - 32) * 5/9
    return celsius